/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ATV Remote Control
 * OpenAPI spec version: 1.0
 */
export interface AddDeviceRequest {
  ip: string;
  port: number;
}

export interface ApiResponse {
  success: boolean;
  message: string;
}

export interface DeviceList {
  devices: string[];
}

export interface TextInputRequest {
  text: string;
}

