/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ATV Remote Control
 * OpenAPI spec version: 1.0
 */

export interface AddServerDeviceRequest {
  serial: string;
  server_addr?: string | null;
}