/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ATV Remote Control
 * OpenAPI spec version: 1.0
 */

export interface DiscoveredDeviceResponse {
  id: string;
  identifier: string;
  connection_type: string;
  state: string;
}