/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * ATV Remote Control
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type { AddDeviceRequest, TextInputRequest } from '../model';






export const getDevices = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.get(
      `http://127.0.0.1:8000/devices`,{
    ...options,}
    );
  }




export const getGetDevicesQueryKey = () => {
    return [
    `http://127.0.0.1:8000/devices`
    ] as const;
    }

    
export const getGetDevicesQueryOptions = <TData = Awaited<ReturnType<typeof getDevices>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDevicesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDevices>>> = ({ signal }) => getDevices({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDevicesQueryResult = NonNullable<Awaited<ReturnType<typeof getDevices>>>
export type GetDevicesQueryError = AxiosError<unknown>


export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevices>>,
          TError,
          Awaited<ReturnType<typeof getDevices>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevices>>,
          TError,
          Awaited<ReturnType<typeof getDevices>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDevices<TData = Awaited<ReturnType<typeof getDevices>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDevices>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDevicesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const postDevices = (
    postDevicesBody: AddDeviceRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `http://127.0.0.1:8000/devices`,
      postDevicesBody,{
    ...options,}
    );
  }



export const getPostDevicesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: AddDeviceRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: AddDeviceRequest}, TContext> => {

const mutationKey = ['postDevices'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDevices>>, {data: AddDeviceRequest}> = (props) => {
          const {data} = props ?? {};

          return  postDevices(data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostDevicesMutationResult = NonNullable<Awaited<ReturnType<typeof postDevices>>>
    export type PostDevicesMutationBody = AddDeviceRequest
    export type PostDevicesMutationError = AxiosError<unknown>

    export const usePostDevices = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevices>>, TError,{data: AddDeviceRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDevices>>,
        TError,
        {data: AddDeviceRequest},
        TContext
      > => {
      return useMutation(getPostDevicesMutationOptions(options), queryClient);
    }
    export const deleteDevicesIp = (
    ip: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.delete(
      `http://127.0.0.1:8000/devices/${ip}`,{
    ...options,}
    );
  }



export const getDeleteDevicesIpMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIp>>, TError,{ip: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIp>>, TError,{ip: string}, TContext> => {

const mutationKey = ['deleteDevicesIp'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDevicesIp>>, {ip: string}> = (props) => {
          const {ip} = props ?? {};

          return  deleteDevicesIp(ip,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDevicesIpMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDevicesIp>>>
    
    export type DeleteDevicesIpMutationError = AxiosError<unknown>

    export const useDeleteDevicesIp = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDevicesIp>>, TError,{ip: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDevicesIp>>,
        TError,
        {ip: string},
        TContext
      > => {
      return useMutation(getDeleteDevicesIpMutationOptions(options), queryClient);
    }
    export const postDevicesIpKeyKeyName = (
    ip: string,
    keyName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `http://127.0.0.1:8000/devices/${ip}/key/${keyName}`,undefined,{
    ...options,}
    );
  }



export const getPostDevicesIpKeyKeyNameMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>, TError,{ip: string;keyName: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>, TError,{ip: string;keyName: string}, TContext> => {

const mutationKey = ['postDevicesIpKeyKeyName'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>, {ip: string;keyName: string}> = (props) => {
          const {ip,keyName} = props ?? {};

          return  postDevicesIpKeyKeyName(ip,keyName,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostDevicesIpKeyKeyNameMutationResult = NonNullable<Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>>
    
    export type PostDevicesIpKeyKeyNameMutationError = AxiosError<unknown>

    export const usePostDevicesIpKeyKeyName = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>, TError,{ip: string;keyName: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDevicesIpKeyKeyName>>,
        TError,
        {ip: string;keyName: string},
        TContext
      > => {
      return useMutation(getPostDevicesIpKeyKeyNameMutationOptions(options), queryClient);
    }
    export const postDevicesIpInputText = (
    ip: string,
    postDevicesIpInputTextBody: TextInputRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `http://127.0.0.1:8000/devices/${ip}/input/text`,
      postDevicesIpInputTextBody,{
    ...options,}
    );
  }



export const getPostDevicesIpInputTextMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpInputText>>, TError,{ip: string;data: TextInputRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpInputText>>, TError,{ip: string;data: TextInputRequest}, TContext> => {

const mutationKey = ['postDevicesIpInputText'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDevicesIpInputText>>, {ip: string;data: TextInputRequest}> = (props) => {
          const {ip,data} = props ?? {};

          return  postDevicesIpInputText(ip,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostDevicesIpInputTextMutationResult = NonNullable<Awaited<ReturnType<typeof postDevicesIpInputText>>>
    export type PostDevicesIpInputTextMutationBody = TextInputRequest
    export type PostDevicesIpInputTextMutationError = AxiosError<unknown>

    export const usePostDevicesIpInputText = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDevicesIpInputText>>, TError,{ip: string;data: TextInputRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDevicesIpInputText>>,
        TError,
        {ip: string;data: TextInputRequest},
        TContext
      > => {
      return useMutation(getPostDevicesIpInputTextMutationOptions(options), queryClient);
    }
    